--USERS SCRIPT

DROP USER CONSTITADMIN;
CREATE USER CONSTITADMIN IDENTIFIED BY Constit123456;
grant connect to CONSTITADMIN; 
GRANT CREATE SESSION TO CONSTITADMIN;
grant EXECUTE ON PKG_CONSTITUENCY to CONSTITADMIN;
grant EXECUTE ON pkg_POSITION to CONSTITADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSTITUENCY TO CONSTITADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON POSITION TO CONSTITADMIN;

--
DROP USER ELECTORALADMIN;
CREATE USER ELECTORALADMIN IDENTIFIED BY Elect123456789;
grant connect to ELECTORALADMIN; 
GRANT CREATE SESSION TO ELECTORALADMIN;
grant EXECUTE ON pkg_position to ELECTORALADMIN;
grant EXECUTE ON pkg_candidate to ELECTORALADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON candidate TO ELECTORALADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON position TO ELECTORALADMIN;

----
DROP USER UANADMIN;
CREATE USER UANADMIN IDENTIFIED BY Uan123456789;
grant connect to UANADMIN; 
GRANT CREATE SESSION TO UANADMIN;
grant EXECUTE ON pkg_people to UANADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON people TO UANADMIN;

--

DROP USER PARTYADMIN;
CREATE USER PARTYADMIN IDENTIFIED BY Party123456789;
grant connect to PARTYADMIN; 
GRANT CREATE SESSION TO PARTYADMIN;
grant EXECUTE ON pkg_party to PARTYADMIN;
grant EXECUTE ON pkg_candidate to PARTYADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON candidate TO PARTYADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON party TO PARTYADMIN;

--
DROP USER CommunityADMIN;
CREATE USER CommunityADMIN IDENTIFIED BY Commu123456789;
grant connect to CommunityADMIN; 
GRANT CREATE SESSION TO CommunityADMIN;
grant EXECUTE ON PKG_STATE to CommunityADMIN;
grant EXECUTE ON pkg_PEOPLE to CommunityADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON STATE TO CommunityADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PEOPLE TO CommunityADMIN;


---
DROP USER ELECTIONCOMMISSIONADMIN;
CREATE USER ELECTIONCOMMISSIONADMIN IDENTIFIED BY Com123456789;
grant connect to ELECTIONCOMMISSIONADMIN; 
GRANT CREATE SESSION TO ELECTIONCOMMISSIONADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON VOTEs TO ELECTIONCOMMISSIONADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON VOTER TO ELECTIONCOMMISSIONADMIN;

--




