create or replace procedure DELETE_party
(P_ID IN PARTY.PARTY_ID%TYPE)
IS 
EXECP1 EXCEPTION;
EXECP2 EXCEPTION;
BEGIN
IF(PARTY_EXISTS(P_ID)=0) THEN RAISE EXECP1;
ELSIF (P_ID IS NULL) THEN RAISE EXECP2;--
ELSE 
DELETE FROM PARTY WHERE PARTY_ID= P_ID;
END IF; 
EXCEPTION 
    WHEN EXECP1 THEN 
    DBMS_OUTPUT.PUT_LINE('That party ID doesnt exists, please enter a valid party ID');
    WHEN EXECP2 THEN 
    DBMS_OUTPUT.PUT_LINE('Please enter a valid party ID');
END DELETE_PARTY;